# Generated by Django 5.2.11 on 2026-03-11 03:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='committee_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='category',
            field=models.CharField(choices=[('executive', 'Executive Board'), ('committee', 'Committee'), ('general', 'General Member')], default='executive', max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
