# Generated by Django 5.2.11 on 2026-03-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_teammember_committee_title_alter_teammember_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('all', 'All Events'), ('service-project', 'Service-Project'), ('professional-development', 'Professional Development'), ('international-relation', 'International Relation'), ('club-admin-and-fellowship', 'Club Admin and Fellowship')], default='all', max_length=50),
        ),
    ]
