# Generated by Django 5.2.11 on 2026-03-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('all', 'All Photos'), ('service-project', 'Service-Project'), ('professional-development', 'Professional Development'), ('international-relation', 'International Relation'), ('club-admin-and-fellowship', 'Club Admin and Fellowship')], default='all', max_length=50),
        ),
    ]
