# Generated by Django 5.2.11 on 2026-03-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
